FROM amazon/aws-cli:latest

# 1. Install kubectl
# We fetch the latest stable version and move it to the path
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/

# 2. Create the refresh script
COPY refresh-ecr.sh /usr/local/bin/refresh-ecr.sh
RUN chmod +x /usr/local/bin/refresh-ecr.sh

# Set the script as the entrypoint
ENTRYPOINT ["/usr/local/bin/refresh-ecr.sh"]