apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-credential-refresher
spec:
  schedule: "*/5 * * * *" # This schedule runs the job every minute. Adjust as needed.
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ecr-refresh-sa
          restartPolicy: OnFailure
          containers:
          - name: refresher
            image: 702175642104.dkr.ecr.us-east-1.amazonaws.com/abhishek-ecr/abhishek-ecr:$cron_image_name-$TAG
            env:
            - name: REGION
              value: "us-east-1" # Change to your region
            - name: ACCOUNT_ID
              value: "702175642104" # Change to your AWS Account ID
            - name: SECRET_NAME
              value: "ecr-pull-image-secret"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-bridge-creds
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-bridge-creds
                  key: secret-key
          imagePullSecrets:
          - name: ecr-pull-image-secret
