apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-refresh-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-refresh-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["ecr-pull-image-secret", "ecr-pull-secret"]
  verbs: ["get", "delete", "create", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-refresh-binding
subjects:
- kind: ServiceAccount
  name: ecr-refresh-sa
roleRef:
  kind: Role
  name: ecr-refresh-role
  apiGroup: rbac.authorization.k8s.io